---
- name: looping and creating users
  hosts: prod
  vars:
    users:
      - kim
      - sim
      - zim
      - fin
  tasks:
    - name: adding multiple users via looping
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ users }}"
